### ISSUE TITLE
Working in different repo

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/multifield#1]
FYI, I am working on this in a different repo. Tried to transfer it here but there was a conflict with this one. I'll figure out how to replace this one once I get it further along...

https://github.com/laryn/multifield

**Comment by klonos** [comment]
@laryn did you create this repo here? If so (or whoever did create it), what was missed is to set admin/full access to the backdrop contrib Authors team. Done that now. Can you give it a go again?

**Comment by laryn** [comment]
@klonos No, I didn't create this one. I think @jenlampton did the early prep work on this one but no actual porting/conversion work. Since there were a number of new commits on Drupal's multifield I didn't start from this base. I still can't transfer the repo from my account because the namespace conflicts. Maybe this one can just be deleted and I can move over the one I'm working on?

**Comment by jenlampton** [comment]
Works for me. Go ahead and force push!
- -
  Please excuse brevity and typos. Message typed with my thumbs from an Open
  Source OS.

**Comment by laryn** [comment]
Done.
