### ISSUE TITLE
Multifield module breaks the settings form for XMLsitemap module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/multifield#12]
I know it seems unlikely, but I'm getting a multifield related db error on the xmlsitemap settings form:
```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'multifield.id' in 'where clause': SELECT COUNT(*) AS expression FROM (SELECT 1 AS expression FROM {multifield} multifield WHERE (multifield.id > :db_condition_placeholder_0) AND (multifield.type = :db_condition_placeholder_1) ) subquery; Array ( [:db_condition_placeholder_0] => 0 [:db_condition_placeholder_1] => field_list_items ) in xmlsitemap_get_link_type_indexed_status() (line 962 of backdrop/modules/contrib/xmlsitemap/xmlsitemap.module).
```

However, disabling the multifield module brought the XMLsitemap admin form back to life.

see related: https://github.com/backdrop-contrib/xmlsitemap/issues/42

**Comment by laryn** [comment]
@jenlampton Just curious -- do you/have you ever had both of these installed on a Drupal site together without getting this?

**Comment by jenlampton** [comment]
I'm not sure!  I'll check as I have a few sites using them both together...

**Comment by jenlampton** [comment]
Yes, I have two Drupal 7 sites running both multifield and xmlsitemap and the settings page for xmlsitemap is still working:
<img width="1450" alt="screen shot 2017-09-06 at 6 33 00 pm" src="https://user-images.githubusercontent.com/397895/30141700-e2b54c90-9331-11e7-982e-28f92d6bc8c1.png">

**Comment by laryn** [comment]
@jenlampton I was just testing this with your latest entity work and can't replicate. Then I swapped out the current release and cleared caches...and still have no problems. Are you still having this issue, and can you replicate on a different server?

**Comment by laryn** [comment]
Looks like a fix was also merged in on XML Sitemap so I'll close this here for now. Reopen if there is still an issue.
