### ISSUE TITLE
Issues with Views

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/multifield#13]
When using views and wanting to add a subfield to a view, the subfields are included in the select list but when one is selected the 'add and configure' step does not work. However, the subfield has been added to the view but it is not possible to select it from the resulting list of fields, for example to remove it.

When doing a similar operation to add a subfield to the filter criteria this seems to work correctly and the filter criterion can be configured, also the subfield can be removed from the list of filter criteria.

**Comment by laryn** [comment]
@Graham-72 Sorry I haven't had time to dig deeper on this. Are there any error messages in the log or console?

**Comment by Graham-72** [comment]
@laryn Yes, I have just spotted this

`Error: Call to undefined function views_ui_build_form_url() in MultifieldViewsHandler->options_form() (line 427 of /var/www/vhosts/xxxxxxx.net/httpdocs/backdrop/modules/multifield/includes/MultifieldViewsHandler.php).
`

**Comment by laryn** [comment]
@Graham-72 Can you try swapping out `views_ui_build_form_url()` for `views_ui_build_form_path()` and see if it works in your setup? _(Suggestion by @oadaeh on Gitter)_

**Comment by Graham-72** [comment]
@laryn Thanks, and now I have an error because of this at line 452 in MultifieldViewsHandler
```
    // Provide an instance array for hook_field_formatter_settings_form().
    ctools_include('fields');
    $this->instance = ctools_fields_fake_field_instance($this->definition['subfield_name'],
 '_custom', $formatter, $settings);
```

**Comment by laryn** [comment]
@Graham-72 Can you test the latest commit and see if it solves the issue for you?

**Comment by Graham-72** [comment]
@laryn Thank you, that solves the issue - great!

There is however one thing that I found difficult. When I got to add a new field it appears as Multifield:[label] and when added it is shown in the list of fields in the view like this '
Multifield: First name (First name)' where 'First name' is the field label. This is fine, but when I use the same field as a filter criteria, it is the machine name that is used e.g. 
Content: author:field_first_name_value (= Jeff) - I was using a filter for first name = Jeff.

I think it would be better if the field label rather than the machine name were to be used in both cases.
![screenshot-2017-12-6 test view authors content backdrop starter](https://user-images.githubusercontent.com/10559274/33701656-a6d8dfec-db17-11e7-877a-23de54a1ddc0.png)

**Comment by Graham-72** [comment]
@laryn There is another error report
`
Notice: Undefined variable: formatter_settings in options_form() (line 472 of /var/www/vhosts/xxxxxxx.net/httpdocs/backdrop200/modules/multifield/includes/MultifieldViewsHandler.php).
`

**Comment by laryn** [comment]
@Graham-72 I'll see if I can sort this at some point soon although Views code is still a little hairy for me. Or, if you have an idea, feel free to submit a PR.

**Comment by laryn** [comment]
@Graham-72 Just saw this commit -- is it a WIP or ready to test?

**Comment by Graham-72** [comment]
I think this solves my initial problem that caused me to create this issue but I am still testing and trying to see if anything can be done to rationalise the field and subfield labelling in the UI, which is what caused me to identify #18.

**Comment by Graham-72** [comment]
@laryn I have now found a way to modify the references to subfields that appear in Views UI when adding a filter. In an extra commit https://github.com/backdrop-contrib/multifield/pull/19/commits/7e16af6255dd696de36091d39592b1d810901bd3 to my PR, I make a small addition to the hook function multifield_field_views_data. I do not fully understand how this Views function works but this addition seems to work satisfactorily with the very limited testing I have done so far.

New screenshot from test site:
![screenshot-2018-1-9 test view authors content backdrop starter](https://user-images.githubusercontent.com/10559274/34728939-352f771a-f553-11e7-8a7f-193d18bc4d02.png)

**Comment by laryn** [comment]
Thanks, @Graham-72!
I did some testing. Here's a before and after shot of a test install:

**BEFORE:**
![screenshot from 2018-01-11 06-52-17](https://user-images.githubusercontent.com/871421/34826451-2ef20698-f69c-11e7-8c1d-3d806f759093.png)

**AFTER:**
![screenshot from 2018-01-11 06-53-26](https://user-images.githubusercontent.com/871421/34826459-3845119a-f69c-11e7-836a-b88486e52fcc.png)

So: definite improvement! But maybe something still going on when the filter is exposed -- can you test further in that regard?

**Comment by laryn** [comment]
Also, in terms of UI it might also be good to use labels when adding these to the View. e.g.

![screenshot from 2018-01-11 06-57-43](https://user-images.githubusercontent.com/871421/34826602-db29efe8-f69c-11e7-8191-98909b289794.png)

What do you think about that?

**Comment by Graham-72** [comment]
@laryn 

>But maybe something still going on when the filter is exposed -- can you test further in that regard?

I will have a look again at this but at the moment my test site is not giving the same result as yours.
![screenshot-2018-1-11 test view authors content backdrop starter](https://user-images.githubusercontent.com/10559274/34834191-441f24fe-f6e9-11e7-843d-959dc8f117d0.png)

**Comment by jenlampton** [comment]
I wonder if many of the field label issues might not be related to https://github.com/backdrop-contrib/multifield/issues/18.  Can either of you try that fix and see if it helps with this?

**Comment by jenlampton** [comment]
I just ran into this too, and will be pushing up a fix shortly :)

**Comment by jenlampton** [comment]
Well, I thought I had a fix ready for this, but when I pulled the latest from dev, it appears my new solution was actually an old solution, and has been included already. :/ I'm going to mark this issue as resolved, and make a new release. If anyone experiences this again, please re-open.
