### ISSUE TITLE
Multifield database table is empty

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/multifield#15]
As I was working on https://github.com/backdrop-contrib/multifield/issues/14 I noticed that the database table for Multifields was empty, in spite of my site having plenty of multifield values. If this table isn't needed anymore, perhaps it should be removed? If it is needed, we should find out why it's not being used, and fix that :)

**Comment by laryn** [comment]
@jenlampton, agreed. I just verified the same on my site. Do you have multifield on a D7 install somewhere yet? If so -- what type of info is stored in the db?

**Comment by jenlampton** [comment]
I do. Let me try to remember which one, and see what's in there...

**Comment by jenlampton** [comment]
Hah! It's empty in Drupal 7 too :)  Let's write an update hook that removes the table and remove the `hook_schema()`.

**Comment by jenlampton** [comment]
Posted a PR to remove this table: https://github.com/backdrop-contrib/multifield/pull/30
