### ISSUE TITLE
Create a multifield Entity, instead of using stdClass

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/multifield#16]
While working on https://github.com/backdrop-contrib/multifield/issues/14 (which turned out to be unrelated) I had created a Multifield Entity instead of using stdClass, which might still be a good idea.

**Comment by laryn** [comment]
@jenlampton Sounds good to me -- have you tested/swapped this in on a site that was using Multifield already?

**Comment by jenlampton** [comment]
@laryn no, I only used it on my demo site. Then I realized this wasn't the stdClass object that was causing me headaches, so I stopped testing :)

**Comment by laryn** [comment]
@jenlampton I swapped it in on a site running Multifield and from my testing everything seems to be running along just fine. Would you be willing to test with some actual real-world data before I merge?

**Comment by jenlampton** [comment]
Sure. Want me to run a patched version on one of my sites for a while, or?

**Comment by laryn** [comment]
Sounds great. Thanks!
