### ISSUE TITLE
Field label not appearing in Multifields listing.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/multifield#18]
In the admin table lising the multifields the machine name appears in the label column as well as the machine name column.
![screenshot-2018-1-3 multifields catherine larner](https://user-images.githubusercontent.com/10559274/34617623-f7883a4a-f233-11e7-81c1-5a1da6d44d2a.png)

I have worked out a way to get the label there and will provide a PR, though my code may not be the best solution.
![screenshot-2018-1-5 multifields catherine larner](https://user-images.githubusercontent.com/10559274/34617739-583a3ae6-f234-11e7-853e-bd5357514dbc.png)

---
Pull request is at https://github.com/backdrop-contrib/multifield/pull/19.
Another PR available: https://github.com/backdrop-contrib/multifield/pull/23

**Comment by laryn** [comment]
@Graham-72 Thanks! Interestingly, I just double checked and it looks like this issue exists in the Drupal version of multifield as well.

@jenlampton If you have a moment to glance at this with another set of eyes, does it seem reasonable to you?

**Comment by jenlampton** [comment]
Feedback left at https://github.com/backdrop-contrib/multifield/pull/19#issuecomment-355609292

**Comment by Graham-72** [comment]
Thanks @jenlampton for your feedback and suggestion. I have added commit https://github.com/backdrop-contrib/multifield/pull/19/commits/7e16af6255dd696de36091d39592b1d810901bd3 to the PR.

**Comment by laryn** [comment]
@Graham-72 I've tested and the latest PR does fix the label on this page. There's something still going on with Views, I think, which I've noted [over there](https://github.com/backdrop-contrib/multifield/issues/13).

**Comment by jenlampton** [comment]
I think we just need to add a `'bundle label' => t('Multifield type'),` line to `hook_entity_info()`. Filing  PR now.

**Comment by laryn** [comment]
@jenlampton or @Graham-72 Sidebar question: Are either of you interested in being co-maintainers here? I'm not sure when I'll next have time to devote to Multifield.

**Comment by jenlampton** [comment]
@laryn Yes I'd be interested. I'm using it on several sites and am highly motivated to keep it up to date :)

**Comment by laryn** [comment]
@jenlampton Just added you.

**Comment by Graham-72** [comment]
👍

**Comment by jenlampton** [comment]
Filed a PR for being a co-maintainer: https://github.com/backdrop-contrib/multifield/pull/26

**Comment by jenlampton** [comment]
Latest patch didn't apply cleanly against HEAD, rebased. 

Still looks fixed?
<img width="1218" alt="Screen Shot 2020-02-21 at 11 09 41 AM" src="https://user-images.githubusercontent.com/397895/75063891-b402ca80-549a-11ea-976f-fc3256e6f864.png">
