### ISSUE TITLE
Upgrade path

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/multifield#2]
See "Create an upgrade path" here:
https://api.backdropcms.org/converting-modules-from-drupal

**Comment by laryn** [comment]
Anyone with more experience of multisite -- is there anything further needed for this upgrade path? As far as I can see there are no global multisite variables, it's all field-specific. Will those be handled by the system upgrade for people coming from Drupal?

**Comment by jenlampton** [comment]
> Will those be handled by the system upgrade for people coming from Drupal?

Most field-specific settings don't change at all between Drupal + Backdrop (and yes, the system upgrade will convert them to config).
