### ISSUE TITLE
Multifield prevents update to Backdrop 1.13.0

### ISSUE THREAD

**Issue by kthull** [backdrop-contrib/multifield#24]
When updating to the 1.13.0 version of Backdrop core, Multifield throws the following error. 

`Error: Call to undefined function multifield_extract_multifield_machine_name() in multifield_field_schema() (line 66 of /app/docroot/modules/contrib/multifield/multifield.install).`

If I remove the module files from the docroot, the update proceeds without error. If I put the files back, the site at first appears to work until I clear cache, and then I get the above error again. Removing the files and clearing cache again will restore the site.

**Comment by jenlampton** [comment]
Looks like we may be missing a call to 
```php
module_load_include('module', 'multifield', 'multifield');
```

**Comment by kthull** [comment]
Confirmed adding that to line 66 in multifield.install fixes the error.

**Comment by jenlampton** [comment]
Committed the fix, thanks @kthull

**Comment by jenlampton** [comment]
Commit added, closing this issue.
