### ISSUE TITLE
Fatal error, need to update EntityInterface entityType to be static

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/multifield#27]
This is the same as https://github.com/backdrop-contrib/flag/issues/14

Core had an API change. Need an update here like this:

```php
          /**
		   * Implements EntityInterface::entityType().
		   *
		   * @since 1.13.0 This method is now static.
		   */
		  public static function entityType() {
		    return 'entity_test';
		  }
```

**Comment by jenlampton** [comment]
PR filed: https://github.com/backdrop-contrib/multifield/pull/28

**Comment by quicksketch** [comment]
This API change is being reverted in core https://github.com/backdrop/backdrop-issues/issues/3809

**Comment by jenlampton** [comment]
Great, closing this issue. The core change will make this change unnecessary (and problematic)
