### ISSUE TITLE
Data loss: images uploaded via rich-text editor never marked as permanent

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/multifield#29]
A client of mine had loaded about 16 images into 16 text fields via the rich-text editor, and when he came back a day later, all the embedded images had been deleted from disk.

It looks like the normal `_filter_record_file_usage()` doesn't work on multifields.

**Comment by laryn** [comment]
@jenlampton In case it's a similar issue, look here: https://github.com/backdrop-contrib/paragraphs/issues/14

**Comment by jenlampton** [comment]
It does sound similar, but the two commits there only add a bundle method, and multifield already has that. 

With paragraphs, the core entity hooks should work because the parent (a paragraph) is an entity, and the text values containing FIDs are in fields on the entity. With multifield, the parent is really only a field (with a configuration entity), and the sub-fields are not accessible at `$entity->field` which is what the core hooks are looking for. 

I'm currently working on adding my own implementations of `hook_entity_insert()` and `hook_entity_update()` that will parse multifield values too.

**Comment by jenlampton** [comment]
PR that should fix this problem: https://github.com/backdrop-contrib/multifield/pull/31 
I'm running this on a few production sites now, will report back if there are any issues.

**Comment by jenlampton** [comment]
Everything is working nicely now. I'm going to merge this PR.
