### ISSUE TITLE
Feeds importer support

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/multifield#39]
I need to import a bunch of data from CSV spreadsheets, and would like my multifields to be populated from the sheet. 

I've got imports running with this change but would love help testing!

**Comment by olafgrabienski** [comment]
Thanks for the PR! After adding the new `multifield.feeds.inc` file to a test site, I was able to import from a CSV file into multifield (subfields). So, works for me!

One minor issue: At `admin/structure/feeds/node_import/mapping` in the *Legend* fieldset, there is no description for my multifields, only the name. For other targets, there is a name and description, e.g. `Tags (field_tags) | The Tags field of the entity.`

**Comment by jenlampton** [comment]
I have copied your feedback into another issue so that I can merge this PR for the next release, but the note won't get lost. Thanks for testing!
