### ISSUE TITLE
Whitescreen during update to 1.x-1.0.0

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/multifield#46]
When running `update.php` during the update of Multifield from `1.x-1.0.0-beta3` to `1.x-1.0.0`, I get a white screen with the following notice:

> Fatal error: require_once(): Failed opening required '/.../modules/multifield/includes/MultifieldEntityController.php' (include_path='.:') in /.../core/includes/bootstrap.inc on line 4029

With this, I couldn't access any page of the site until I uploaded the `beta3` version again.

**Comment by oadaeh** [comment]
Did you try clearing your caches after updating the module? It might be that you have to do it with Drush or Bee.

**Comment by olafgrabienski** [comment]
Thanks for the hint! I didn't try to clear cache (not possible due to lack of UI). Not sure if I can install Drush or Bee on that shared hosting, will try it.

**Comment by olafgrabienski** [comment]
After installing *Bee* I tried the update again, and this time it ran without issues (without the need to use *Bee*).

(Closing as I can't reproduce the issue anymore.)

**Comment by olafgrabienski** [comment]
The issue happened again on another site. Again no Drush or Bee on the server, but this time I was able to access the site after changing the database host in `setttings.php` temporarily from `localhost` to `127.0.0.1`. (Unfortunately I forgot where I got the hint for this workaround.)
