### ISSUE TITLE
file_field_update() invocation in _multifield_field_invoke() results in fatal error.

### ISSUE THREAD

**Issue by eric2pin** [backdrop-contrib/multifield#47]
Hello,

When saving a node that has multifields configured which include a file upload field, I receive the following fatal error: Error: Call to undefined method stdClass::id() in file_field_update() (line 247 of /core/modules/file/file.field.inc).

file_field_update(), called in _multifield_field_invoke() in multifield.field.inc line 395, is looking for the entity->id() and failing because the object passed to it is created by _multifield_field_item_to_entity() which returns a stdClass "pseudo element" with no entity->id() method.

I am able to temporarily solve the problem by defining a PseudoElement entity elsewhere in my code and casting the item passed to _multifield_field_item_to_entity() to the PseudoElement entity class instead, for which I have defined a PseudoElement->id(). Basically adding $pseudo_element = cast_to_my_custom_entity($pseudo_element); on lines 384 / 389.

It seems all entities now need an entity->id() method to interact properly with the rest of field api in core. What is the correct fix for this problem?

Thanks much,

**Comment by laryn** [comment]
I believe at this point this is fixed (back in https://github.com/backdrop-contrib/multifield/issues/32).
