### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/multifield#52]
Unfortunately in a fairly prominent place!

https://github.com/search?q=repo%3Abackdrop-contrib%2Fmultifield%20Psuedo&type=code

 - `MultifieldPsuedoEntity` should be `MultifieldPseudoEntity`

**Comment by laryn** [comment]
@argiepiano Curious if you have a recommendation on this type of thing with renaming a class due to a spelling error. Would I then need to redeclare the mis-spelled class extending the correctly spelled class but with no changes (for backwards compatibility)?

**Comment by argiepiano** [comment]
At quick sight, this seems to be a safe class to rename. It's instantiated internally on page requests, and its class name is not stored anywhere. The entity itself is not stored either. I'd just change it wherever it's misspelled.  There shouldn't be any issues with backward compatibility.

**Comment by laryn** [comment]
Thanks for taking a quick peek. I was mostly wondering about the (remote?) possibility that someone in custom code may have extended the mis-spelled class.

**Comment by argiepiano** [comment]
I really doubt that. If anything, someone may extend the "real" class that is used for multifield entities. This class is just a temporary storage for processing field items, I think. All this after a quick glance.

**Comment by laryn** [comment]
> All this after a quick glance.

Disclaimer noted -- I accept full responsibility for what I'm about to do. 😄
