### ISSUE TITLE
Efficiency question

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/multifield#53]
I have a site with a lot of fields and even on my local it's very slow to load (for example) the admin pages to add/edit a content type's fields. I turned on XHProf and have identified Multifield as the reason, in particular the `multifield_field_schema` function:

<img width="1580" alt="image" src="https://github.com/backdrop-contrib/multifield/assets/871421/df0f59f1-8b71-477f-a42a-8a9e1aea5f9b">

That function specifically avoids using caching "to ensure we're using the most current data" -- but I'm wondering if that cost is worth it. @jenlampton What are your thoughts -- should we cache inside that schema function?

_EDIT: Updating to make sure that I'm comparing apples to apples. Not necessarily the most dramatic example from this site, but still shows the issue._

**Comment by laryn** [comment]
For comparison, here's the same page loaded after I hacked in a change to use the cache (by pulling `$field_names` through the `multifield_type_get_subfields` function):

<img width="1613" alt="image" src="https://github.com/backdrop-contrib/multifield/assets/871421/3b47293f-e4dd-4ae3-8f60-cdf46557019e">

**Comment by laryn** [comment]
Another point of note: the content type used in the example above does not have any multifields on it.

**Comment by laryn** [comment]
@hosef Suggested also testing by just "changing line 18 of multifield.install from
  `$config_names = config_get_names_with_prefix('field.instance.');`
to
  `$config_names = config_get_names_with_prefix('field.instance.multifield.');`"

Here's how that comes out:

<img width="1615" alt="image" src="https://github.com/backdrop-contrib/multifield/assets/871421/5a6b2a96-98a0-414d-9228-358342bcc657">

**Comment by argiepiano** [comment]
Try making the same change in `multifield_get_subfields()`

**Comment by laryn** [comment]
Good catch -- but in this case it is not calling that function so it didn't have an effect. But it should be changed there I suppose!

**Comment by laryn** [comment]
From @hosef on Zulip:

> I can't see any reason why it is not using the cache. It looks like the coverage for cleaning up the cache entries is pretty solid.
> At the very least, I would put the subfield data in a static variable so that it's not being regenerated 70 times in the same page load.

I'm going to file a PR that uses the `multifield_type_get_subfields` function (and fixes the `multifield_get_subfields` usage of `config_get_names_with_prefix`).

Thanks @argiepiano and @hosef!

**Comment by laryn** [comment]
This is after a cache clear and then immediate page reload (with the PR):

<img width="1582" alt="image" src="https://github.com/backdrop-contrib/multifield/assets/871421/685d4091-bb78-49b3-8455-d33c4d75d945">

Once cache has been built and page reload:

<img width="1598" alt="image" src="https://github.com/backdrop-contrib/multifield/assets/871421/96fe3325-07fb-4093-b08d-0dd592f02015">
