### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/multifield#6]
Seeing a lot of this error in the logs, should be investigated further:

`Notice: Only variables should be passed by reference in multifield_field_schema() (line 81 of /path/to/backdrop/modules/multifield/multifield.install).`

**Comment by docwilmot** [comment]
`$subfields[$name] = reset(field_read_fields(array('field_name' => $name)));`
Change to:
```
$subfield_data = field_read_fields(array('field_name' => $name));
$subfields[$name] = reset($subfield_data);
```

Should do it.

**Comment by laryn** [comment]
https://github.com/backdrop-contrib/multifield/commit/a6b04873aec720292ec4cec57efae31da4b411e3
