### ISSUE TITLE
type => actions

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/multifield#8]
@docwilmot on Gitter

> the 'remove' buttons are being wrapped in a type => actions form element. I just changed it to a type => container element instead.
> Backdrop forces all type => actions elements to the bottom of the dialog.
> So multifield probably shouldnt be using that element type except for submit buttons since anytime we use a multifield in a dialog this would happen

**Comment by laryn** [comment]
@docwilmot Is the above commit all that is needed?

**Comment by docwilmot** [comment]
Also added weight 99 so the delete button stayed last

**Comment by laryn** [comment]
@docwilmot Thanks for taking a peek -- I tried again.

**Comment by laryn** [comment]
Third time's the charm. Closing this and will issue a new release. 

Reopen if I've somehow managed to get it wrong again. ;)
